spring:
  banner:
    location: classpath:/banner/banner.txt  
  datasource:    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password:  
  jpa:    show-sql: true    hibernate:      ddl-auto: update
      
    
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect            
    
server:
  error:
    whitelabel:
      enabled: false
      